# Type stubs for nuke module
from typing import Any, List, Optional, Dict, Union

# Version constants
NUKE_VERSION_MAJOR: int
NUKE_VERSION_MINOR: int
NUKE_VERSION_RELEASE: int

class Node:
    """Nuke node object"""
    def name(self) -> str: ...
    def Class(self) -> str: ...
    def knob(self, name: str) -> Any: ...
    def __getitem__(self, name: str) -> Any: ...

def root() -> Node: ...
def allNodes(node_class: Optional[str] = None) -> List[Node]: ...
def selectedNodes() -> List[Node]: ...
def createNode(node_class: str, knobs: str = "", inpanel: bool = True) -> Node: ...
def delete(node: Node) -> None: ...
def execute(node: Union[Node, str], start: int, end: int, incr: int = 1) -> None: ...
def render(write_node: Union[Node, str], start: int, end: int, incr: int = 1) -> None: ...
def nodePaste(filename: str) -> None: ...
def scriptSave(filename: str) -> None: ...
def scriptOpen(filename: str) -> None: ...
def addCallback(callback: Any, nodeClass: str) -> None: ...
def removeCallback(callback: Any, nodeClass: str) -> None: ...

# Global variables that might be accessed
thisNode: Optional[Node]
thisKnob: Optional[Any]
thisGroup: Optional[Node] 